import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { apiFetcher } from "@/helper/fetcher";
import { IPost } from "@/types/post";
import { Post } from "@/components/Post";

export default function Posts() {
  const [posts, setPosts] = useState<IPost[]>([]);

  useEffect(() => {
    const dataFetcher = async () => {
      const postsData = await apiFetcher<IPost[]>(
        "http://localhost:4000/posts"
      );

      setPosts(postsData);
    };

    dataFetcher();
  }, []);

  return (
    <>
      <Head>
        <title>Client side data fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          {`Here we will see the data accessed by a simple fetch, in a useEffect(
          ). In this case won't pre-render any HTML from the dynamic data.`}
        </h1>
        <br />
        <br />
        <br />
        <br />
        <div>
          {posts.map((post: IPost) => {
            return (
              <div key={post.id}>
                <Post {...post} />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
