import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { apiFetcher } from "@/helper/fetcher";
import { IPost } from "@/types/post";
import { Post } from "@/components/Post";
import useSWR from "swr";

export default function Posts() {
  const dataFetcher = async () => {
    const postsData = await apiFetcher<IPost[]>("http://localhost:4000/posts");

    return postsData;
  };

  const { data, error } = useSWR("posts", dataFetcher);

  if (error) {
    return (
      <div>
        <h1>An unexpected error occured.</h1>
      </div>
    );
  }

  if (!data) {
    return (
      <div>
        <h1>Loading...</h1>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Client side data fetch with SWR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          {`Here we will see the data accessed by a simple fetch, in a useEffect(
          ). In this case won't pre-render any HTML from the dynamic data.`}
        </h1>
        <br />
        <br />
        <br />
        <br />
        <div>
          {data.map((post: IPost) => {
            return (
              <div key={post.id}>
                <Post {...post} />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
