import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetStaticPropsResult } from "next";
import { apiFetcher } from "@/helper/fetcher";
import { IPost, IPostList } from "@/types/post";
import { Post } from "@/components/Post";

export default function Posts({ posts }: IPostList) {
  return (
    <>
      <Head>
        <title>SSG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          Here we will se the data accessed by the getStaticProps( ). The server
          pre-renders our data.
        </h1>
        <br />
        <br />
        <br />
        <br />
        <div>
          {posts.map((post: IPost) => {
            return (
              <div key={post.id}>
                <Post {...post} />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps(): Promise<
  GetStaticPropsResult<IPostList>
> {
  const postsData = await apiFetcher<IPost[]>("http://localhost:4000/posts");

  return {
    props: {
      posts: postsData,
    },
  };
}
